# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Filter
version:      1.01
version_from: lib/Email/Filter.pm
installdirs:  site
requires:
    Class::Trigger:                0
    Email::LocalDelivery:          0.04
    Email::Simple:                 1.1
    IPC::Run:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
