--- #YAML:1.0
name:                Email-Filter
version:             1.031
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Trigger:                0.08
    Email::LocalDelivery:          0.07
    Email::Simple:                 1.91
    IPC::Run:                      0.77
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
